### ISSUE TITLE
what you can expect from node.js 10

### ISSUE THREAD

**Issue by yanyixin** [yued-fe/y-translation#13]
原文地址：[原文地址](https://nodesource.com/blog/what-you-can-expect-from-node-js-10) 

markdown地址：[markdown地址](https://github.com/yued-fe/y-translation/blob/master/todo/What-You-Can-Expect-From-Node.js-10.md)

**Comment by ASkyBig** [comment]
翻译认领-2018-04-28 @yanyixin
