### ISSUE TITLE
How To Write Better Code In React 

### ISSUE THREAD

**Issue by wenkangzhou** [yued-fe/y-translation#14]
- 原文链接：[How To Write Better Code In React](https://blog.bitsrc.io/how-to-write-better-code-in-react-best-practices-b8ca87d462b0)
- Markdown文件：[文件地址](https://github.com/yued-fe/y-translation/blob/master/todo/how-to-write-better-code-in-react-best-practices.md)

**Comment by ASkyBig** [comment]
翻译认领-2018-04-23 @yanyixin
