### ISSUE TITLE
How CSS works: Parsing & painting CSS in the critical rendering path

### ISSUE THREAD

**Issue by foru17** [yued-fe/y-translation#29]
原文地址：https://blog.logrocket.com/how-css-works-parsing-painting-css-in-the-critical-rendering-path-b3ee290762d3
md地址：https://github.com/yued-fe/y-translation/blob/master/todo/how-css-works-parsing-painting-css-in-the-critical-rendering-path.md

**Comment by zuoxue0119** [comment]
@yanyixin 二校认领
