### ISSUE TITLE
A Strategy Guide To CSS Custom Properties

### ISSUE THREAD

**Issue by popeyesailorman** [yued-fe/y-translation#30]
原文地址：https://www.smashingmagazine.com/2018/05/css-custom-properties-strategy-guide/?utm_source=CSS-Weekly&utm_campaign=Issue-315&utm_medium=web
md地址：https://github.com/yued-fe/y-translation/blob/master/todo/A%20Strategy%20Guide%20To%20CSS%20Custom%20Properties.md

**Comment by yanyixin** [comment]
#31

**Comment by yanyixin** [comment]
pr 地址 #31
